export const THEMES = {
  nature_premium: {
    id: 'nature_premium',
    label: 'Nature Premium',
    style: 'bio, cosmétique, artisanat',
    colors: {
      primary:    '#556B2F',
      accent:     '#CC5959',
      highlight:  '#E6B35A',
      background: '#E3DAC9',
      text:       '#2d3a1a',
      textMuted:  '#6b5a3a',
      surface:    'rgba(227, 218, 201, 0.55)',
      btn:        '#556B2F',
      btnText:    '#ffffff',
      btnHover:   '#3d4e20',
    },
  },
  wellness_minimal: {
    id: 'wellness_minimal',
    label: 'Wellness Minimal',
    style: 'bien-être, skincare',
    colors: {
      primary:    '#6B7280',
      accent:     '#AEB8A0',
      highlight:  '#D7EFFF',
      background: '#f0f4f8',
      text:       '#374151',
      textMuted:  '#6B7280',
      surface:    'rgba(255, 255, 255, 0.55)',
      btn:        '#6B7280',
      btnText:    '#ffffff',
      btnHover:   '#4B5563',
    },
  },
  energie_ecommerce: {
    id: 'energie_ecommerce',
    label: 'Énergie e-commerce',
    style: 'marketplace, promos',
    colors: {
      primary:    '#FF5C34',
      accent:     '#1A1A1A',
      highlight:  '#FFDAB9',
      background: '#1A1A1A',
      text:       '#1A1A1A',
      textMuted:  '#555555',
      surface:    'rgba(255, 255, 255, 0.55)',
      btn:        '#FF5C34',
      btnText:    '#ffffff',
      btnHover:   '#e04020',
    },
  },
  luxe_moderne: {
    id: 'luxe_moderne',
    label: 'Luxe moderne',
    style: 'mode haut de gamme',
    colors: {
      primary:    '#6B3F4B',
      accent:     '#C0A080',
      highlight:  '#C0A080',
      background: '#351E28',
      text:       '#351E28',
      textMuted:  '#7a5a65',
      surface:    'rgba(248, 250, 252, 0.55)',
      btn:        '#6B3F4B',
      btnText:    '#F8FAFC',
      btnHover:   '#4a2a35',
    },
  },
  tech_futuriste: {
    id: 'tech_futuriste',
    label: 'Tech futuriste',
    style: 'tech, SaaS',
    colors: {
      primary:    '#4A00E0',
      accent:     '#00FFA3',
      highlight:  '#00FFA3',
      background: '#1A1A1A',
      text:       '#1A1A1A',
      textMuted:  '#555555',
      surface:    'rgba(230, 230, 250, 0.45)',
      btn:        '#4A00E0',
      btnText:    '#ffffff',
      btnHover:   '#3500a8',
    },
  },
  chocolat_chic: {
    id: 'chocolat_chic',
    label: 'Chocolat chic',
    style: 'luxe artisanal',
    colors: {
      primary:    '#3E2723',
      accent:     '#A1887F',
      highlight:  '#F4D8B8',
      background: '#F4D8B8',
      text:       '#3E2723',
      textMuted:  '#8D6E63',
      surface:    'rgba(244, 216, 184, 0.55)',
      btn:        '#3E2723',
      btnText:    '#F4D8B8',
      btnHover:   '#2a1a17',
    },
  },
  citrus_moderne: {
    id: 'citrus_moderne',
    label: 'Citrus moderne',
    style: 'jeunes marques',
    colors: {
      primary:    '#FF6B6B',
      accent:     '#FFC300',
      highlight:  '#FFC300',
      background: '#FFF7ED',
      text:       '#333333',
      textMuted:  '#666666',
      surface:    'rgba(255, 247, 237, 0.60)',
      btn:        '#FF6B6B',
      btnText:    '#ffffff',
      btnHover:   '#e04f4f',
    },
  },
  pastel_digital: {
    id: 'pastel_digital',
    label: 'Pastel digital',
    style: 'apps & UX',
    colors: {
      primary:    '#B497BD',
      accent:     '#B87333',
      highlight:  '#AADBC8',
      background: '#E5E4E2',
      text:       '#3d3540',
      textMuted:  '#7a6b80',
      surface:    'rgba(229, 228, 226, 0.58)',
      btn:        '#B497BD',
      btnText:    '#ffffff',
      btnHover:   '#9a7da5',
    },
  },
  terre_vibrante: {
    id: 'terre_vibrante',
    label: 'Terre vibrante',
    style: 'éco-brand',
    colors: {
      primary:    '#CC5500',
      accent:     '#556B2F',
      highlight:  '#A0522D',
      background: '#F5F5DC',
      text:       '#3a2010',
      textMuted:  '#8a5a30',
      surface:    'rgba(245, 245, 220, 0.58)',
      btn:        '#CC5500',
      btnText:    '#ffffff',
      btnHover:   '#aa4400',
    },
  },
  neon_contraste: {
    id: 'neon_contraste',
    label: 'Néon contrasté',
    style: 'streetwear',
    colors: {
      primary:    '#39FF14',
      accent:     '#00FFFF',
      highlight:  '#39FF14',
      background: '#000000',
      text:       '#000000',
      textMuted:  '#333333',
      surface:    'rgba(255, 255, 255, 0.12)',
      btn:        '#39FF14',
      btnText:    '#000000',
      btnHover:   '#20dd00',
    },
  },
  clean_corporate: {
    id: 'clean_corporate',
    label: 'Clean corporate',
    style: 'e-commerce général',
    colors: {
      primary:    '#1D4ED8',
      accent:     '#F97316',
      highlight:  '#60A5FA',
      background: '#FFFDF7',
      text:       '#1e293b',
      textMuted:  '#64748b',
      surface:    'rgba(255, 253, 247, 0.58)',
      btn:        '#1D4ED8',
      btnText:    '#ffffff',
      btnHover:   '#1638a8',
    },
  },
  banana_soft: {
    id: 'banana_soft',
    label: 'Banana soft',
    style: 'lifestyle',
    colors: {
      primary:    '#264653',
      accent:     '#F4A261',
      highlight:  '#FFF3B0',
      background: '#FFF3B0',
      text:       '#264653',
      textMuted:  '#5a7a88',
      surface:    'rgba(255, 243, 176, 0.58)',
      btn:        '#264653',
      btnText:    '#ffffff',
      btnHover:   '#1a3040',
    },
  },
  mermaidcore: {
    id: 'mermaidcore',
    label: 'Mermaidcore',
    style: 'créatif / beauté',
    colors: {
      primary:    '#7F5AF0',
      accent:     '#00AEEF',
      highlight:  '#00AEEF',
      background: '#1E1E2F',
      text:       '#1E1E2F',
      textMuted:  '#555577',
      surface:    'rgba(192, 192, 192, 0.18)',
      btn:        '#7F5AF0',
      btnText:    '#ffffff',
      btnHover:   '#5f3fc0',
    },
  },
  minimal_chaud: {
    id: 'minimal_chaud',
    label: 'Minimal chaud',
    style: 'boutique moderne',
    colors: {
      primary:    '#111827',
      accent:     '#F59E0B',
      highlight:  '#F59E0B',
      background: '#F8FAFC',
      text:       '#111827',
      textMuted:  '#6B7280',
      surface:    'rgba(248, 250, 252, 0.60)',
      btn:        '#111827',
      btnText:    '#ffffff',
      btnHover:   '#000000',
    },
  },
  green_luxury: {
    id: 'green_luxury',
    label: 'Green luxury',
    style: 'skincare premium',
    colors: {
      primary:    '#0F766E',
      accent:     '#F4D8B8',
      highlight:  '#115E59',
      background: '#FFF7ED',
      text:       '#0c3d38',
      textMuted:  '#4a7a75',
      surface:    'rgba(255, 247, 237, 0.58)',
      btn:        '#0F766E',
      btnText:    '#ffffff',
      btnHover:   '#0a5a53',
    },
  },
  tropical_punch: {
    id: 'tropical_punch',
    label: 'Tropical punch',
    style: 'marques fun',
    colors: {
      primary:    '#118AB2',
      accent:     '#FF4D4D',
      highlight:  '#FFD166',
      background: '#e8fff8',
      text:       '#0a3a4a',
      textMuted:  '#3a8a9a',
      surface:    'rgba(6, 214, 160, 0.12)',
      btn:        '#118AB2',
      btnText:    '#ffffff',
      btnHover:   '#0d6a88',
    },
  },
  authentique_doux: {
    id: 'authentique_doux',
    label: 'Authentique doux',
    style: 'handmade',
    colors: {
      primary:    '#BDB0D0',
      accent:     '#B87333',
      highlight:  '#A0E8AF',
      background: '#F5F5F5',
      text:       '#3a3545',
      textMuted:  '#7a7080',
      surface:    'rgba(245, 245, 245, 0.60)',
      btn:        '#BDB0D0',
      btnText:    '#3a3545',
      btnHover:   '#a09ab8',
    },
  },
  dark_premium: {
    id: 'dark_premium',
    label: 'Dark mode premium',
    style: 'e-commerce luxe moderne',
    colors: {
      primary:    '#C6A7FF',   
      accent:     '#2EE6C9',   
      highlight:  '#FF8FA3',   
      background: '#0A0A0B',   
      surface:    '#141416',        
      text:       '#F5F5F7',  
      textMuted:  '#A1A1AA',        
      btn:        '#C6A7FF',
      btnText:    '#0A0A0B',
      btnHover:   '#A78BFA',   
    },
  },
  automne_chic: {
    id: 'automne_chic',
    label: 'Automne chic',
    style: 'mode / déco',
    colors: {
      primary:    '#8B4513',
      accent:     '#D2691E',
      highlight:  '#D2691E',
      background: '#F5DEB3',
      text:       '#3a1a05',
      textMuted:  '#7a4a25',
      surface:    'rgba(245, 222, 179, 0.58)',
      btn:        '#8B4513',
      btnText:    '#F5DEB3',
      btnHover:   '#6a330f',
    },
  },
  ice_minimal: {
    id: 'ice_minimal',
    label: 'Ice minimal',
    style: 'tech / gadgets',
    colors: {
      primary:    '#0077B6',
      accent:     '#03045E',
      highlight:  '#00B4D8',
      background: '#E0F7FA',
      text:       '#03045E',
      textMuted:  '#0077B6',
      surface:    'rgba(202, 240, 248, 0.55)',
      btn:        '#0077B6',
      btnText:    '#ffffff',
      btnHover:   '#005a8a',
    },
  },
};

export const DEFAULT_THEME = 'dark_premium';