export const THEMES = {
  abyss_deep: {
    id: 'abyss_deep',
    label: 'Abyss Deep',
    style: 'dark oceanic',
    colors: {
      primary:    '#0077B6',
      accent:     '#00B4D8',
      highlight:  '#90E0EF',
      background: '#03045E',
      surface:    'rgba(3, 4, 94, 0.8)',
      card:       'rgba(0, 119, 182, 0.1)',
      border:     'rgba(144, 224, 239, 0.2)',
      text:       '#CAF0F8',
      textMuted:  '#48CAE4',
      btn:        '#0077B6',
      btnText:    '#ffffff',
      btnHover:   '#023E8A',
    },
  },
  solar_flare: {
    id: 'solar_flare',
    label: 'Solar Flare',
    style: 'energy bright',
    colors: {
      primary:    '#FF9F1C',
      accent:     '#FFBF69',
      highlight:  '#FFD6BA',
      background: '#2B2D42',
      surface:    'rgba(255, 255, 255, 0.05)',
      card:       'rgba(255, 159, 28, 0.1)',
      border:     'rgba(255, 191, 105, 0.3)',
      text:       '#FFFFFF',
      textMuted:  '#CBD5E1',
      btn:        '#FF9F1C',
      btnText:    '#2B2D42',
      btnHover:   '#FFBF69',
    },
  },
  moonlight_silver: {
    id: 'moonlight_silver',
    label: 'Moonlight Silver',
    style: 'nocturnal cool',
    colors: {
      primary:    '#C0C0C0',
      accent:     '#E8E8E8',
      highlight:  '#F5F5F5',
      background: '#1A1A1A',
      surface:    'rgba(255, 255, 255, 0.03)',
      card:       'rgba(192, 192, 192, 0.05)',
      border:     'rgba(255, 255, 255, 0.1)',
      text:       '#E0E0E0',
      textMuted:  '#9E9E9E',
      btn:        '#C0C0C0',
      btnText:    '#1A1A1A',
      btnHover:   '#A8A8A8',
    },
  },
  forest_canopy: {
    id: 'forest_canopy',
    label: 'Forest Canopy',
    style: 'nature dense',
    colors: {
      primary:    '#2D6A4F',
      accent:     '#52B788',
      highlight:  '#D8F3DC',
      background: '#1B4332',
      surface:    'rgba(27, 67, 50, 0.7)',
      card:       'rgba(45, 106, 79, 0.4)',
      border:     'rgba(82, 183, 136, 0.2)',
      text:       '#E8F5E9',
      textMuted:  '#95D5B2',
      btn:        '#52B788',
      btnText:    '#1B4332',
      btnHover:   '#40916C',
    },
  },
  desert_dune: {
    id: 'desert_dune',
    label: 'Desert Dune',
    style: 'warm earth',
    colors: {
      primary:    '#C7824C',
      accent:     '#E9A97E',
      highlight:  '#F5D0A9',
      background: '#FDF6E3',
      surface:    'rgba(255, 255, 255, 0.6)',
      card:       '#FFFFFF',
      border:     '#E6D5B8',
      text:       '#5D4037',
      textMuted:  '#8D6E63',
      btn:        '#C7824C',
      btnText:    '#ffffff',
      btnHover:   '#A96C3B',
    },
  },
  arctic_ice: {
    id: 'arctic_ice',
    label: 'Arctic Ice',
    style: 'frozen clean',
    colors: {
      primary:    '#A2D2FF',
      accent:     '#CDB4DB',
      highlight:  '#FFC8DD',
      background: '#F0F4F8',
      surface:    'rgba(255, 255, 255, 0.8)',
      card:       '#FFFFFF',
      border:     '#D6E2E9',
      text:       '#334E68',
      textMuted:  '#627D98',
      btn:        '#A2D2FF',
      btnText:    '#334E68',
      btnHover:   '#82B5FF',
    },
  },
  volcanic_ash: {
    id: 'volcanic_ash',
    label: 'Volcanic Ash',
    style: 'dark industrial',
    colors: {
      primary:    '#FF5733',
      accent:     '#C70039',
      highlight:  '#900C3F',
      background: '#1C1C1C',
      surface:    'rgba(50, 50, 50, 0.5)',
      card:       'rgba(255, 87, 51, 0.05)',
      border:     'rgba(255, 87, 51, 0.2)',
      text:       '#EEEEEE',
      textMuted:  '#AAAAAA',
      btn:        '#FF5733',
      btnText:    '#ffffff',
      btnHover:   '#C70039',
    },
  },
  ocean_breeze: {
    id: 'ocean_breeze',
    label: 'Ocean Breeze',
    style: 'coastal light',
    colors: {
      primary:    '#48CAE4',
      accent:     '#90E0EF',
      highlight:  '#ADE8F4',
      background: '#CAF0F8',
      surface:    'rgba(255, 255, 255, 0.7)',
      card:       '#FFFFFF',
      border:     '#90E0EF',
      text:       '#023E8A',
      textMuted:  '#0077B6',
      btn:        '#0077B6',
      btnText:    '#ffffff',
      btnHover:   '#0096C7',
    },
  },
  royal_gold: {
    id: 'royal_gold',
    label: 'Royal Gold',
    style: 'luxury classic',
    colors: {
      primary:    '#D4AF37',
      accent:     '#F1D476',
      highlight:  '#FFF8DC',
      background: '#0F0F0F',
      surface:    'rgba(20, 20, 20, 0.8)',
      card:       'rgba(212, 175, 55, 0.05)',
      border:     'rgba(212, 175, 55, 0.3)',
      text:       '#F5F5F5',
      textMuted:  '#B8860B',
      btn:        '#D4AF37',
      btnText:    '#0F0F0F',
      btnHover:   '#B8860B',
    },
  },
  cyber_punk: {
    id: 'cyber_punk',
    label: 'Cyber Punk',
    style: 'neon future',
    colors: {
      primary:    '#FF00FF',
      accent:     '#00FFFF',
      highlight:  '#FF0099',
      background: '#050505',
      surface:    'rgba(20, 20, 20, 0.6)',
      card:       'rgba(255, 0, 255, 0.05)',
      border:     'rgba(0, 255, 255, 0.3)',
      text:       '#FFFFFF',
      textMuted:  '#BBBBBB',
      btn:        '#FF00FF',
      btnText:    '#ffffff',
      btnHover:   '#CC00CC',
    },
  },
  vintage_sepia: {
    id: 'vintage_sepia',
    label: 'Vintage Sepia',
    style: 'retro paper',
    colors: {
      primary:    '#704214',
      accent:     '#A67B5B',
      highlight:  '#E8D5C4',
      background: '#F5E6D3',
      surface:    'rgba(255, 255, 255, 0.5)',
      card:       '#FFF8E7',
      border:     '#D2B48C',
      text:       '#3E2723',
      textMuted:  '#5D4037',
      btn:        '#704214',
      btnText:    '#F5E6D3',
      btnHover:   '#5D3510',
    },
  },
  neon_city: {
    id: 'neon_city',
    label: 'Neon City',
    style: 'night life',
    colors: {
      primary:    '#39FF14',
      accent:    '#FF3131',
      highlight:  '#FDFD96',
      background: '#111111',
      surface:    'rgba(30, 30, 30, 0.7)',
      card:       'rgba(57, 255, 20, 0.05)',
      border:     'rgba(57, 255, 20, 0.2)',
      text:       '#FFFFFF',
      textMuted:  '#888888',
      btn:        '#39FF14',
      btnText:    '#000000',
      btnHover:   '#32CC12',
    },
  },
  pastel_dream: {
    id: 'pastel_dream',
    label: 'Pastel Dream',
    style: 'soft fantasy',
    colors: {
      primary:    '#FFB7B2',
      accent:     '#B5EAD7',
      highlight:  '#E2F0CB',
      background: '#FF9AA2',
      surface:    'rgba(255, 255, 255, 0.6)',
      card:       '#FFFFFF',
      border:     '#FFDAC1',
      text:       '#6B5B95',
      textMuted:  '#957DAD',
      btn:        '#FFB7B2',
      btnText:    '#6B5B95',
      btnHover:   '#FF9AA2',
    },
  },
  charcoal_stroke: {
    id: 'charcoal_stroke',
    label: 'Charcoal Stroke',
    style: 'artist dark',
    colors: {
      primary:    '#36454F',
      accent:     '#708090',
      highlight:  '#B0C4DE',
      background: '#1C1C1C',
      surface:    'rgba(54, 69, 79, 0.4)',
      card:       'rgba(112, 128, 144, 0.2)',
      border:     'rgba(176, 196, 222, 0.2)',
      text:       '#E0E0E0',
      textMuted:  '#A9A9A9',
      btn:        '#36454F',
      btnText:    '#ffffff',
      btnHover:   '#2C363F',
    },
  },
  cherry_blossom: {
    id: 'cherry_blossom',
    label: 'Cherry Blossom',
    style: 'spring soft',
    colors: {
      primary:    '#FFB7C5',
      accent:     '#FFC1CC',
      highlight:  '#FFE5E9',
      background: '#FFF0F5',
      surface:    'rgba(255, 255, 255, 0.8)',
      card:       '#FFFFFF',
      border:     '#FFD1DC',
      text:       '#8B4557',
      textMuted:  '#B76E79',
      btn:        '#FFB7C5',
      btnText:    '#8B4557',
      btnHover:   '#FF9EB5',
    },
  },
  midnight_blue: {
    id: 'midnight_blue',
    label: 'Midnight Blue',
    style: 'deep night',
    colors: {
      primary:    '#191970',
      accent:     '#4169E1',
      highlight:  '#6495ED',
      background: '#0B0C10',
      surface:    'rgba(25, 25, 112, 0.3)',
      card:       'rgba(65, 105, 225, 0.1)',
      border:     'rgba(100, 149, 237, 0.2)',
      text:       '#C5C6C7',
      textMuted:  '#66FCF1',
      btn:        '#4169E1',
      btnText:    '#ffffff',
      btnHover:   '#304BB5',
    },
  },
  emerald_city: {
    id: 'emerald_city',
    label: 'Emerald City',
    style: 'vibrant green',
    colors: {
      primary:    '#50C878',
      accent:     '#77DD77',
      highlight:  '#B4F8C8',
      background: '#F0FFF4',
      surface:    'rgba(255, 255, 255, 0.7)',
      card:       '#FFFFFF',
      border:     '#A3E635',
      text:       '#064E3B',
      textMuted:  '#10B981',
      btn:        '#50C878',
      btnText:    '#ffffff',
      btnHover:   '#3CB371',
    },
  },
  ruby_red: {
    id: 'ruby_red',
    label: 'Ruby Red',
    style: 'passion bold',
    colors: {
      primary:    '#E0115F',
      accent:     '#FF0033',
      highlight:  '#FF6666',
      background: '#2C0000',
      surface:    'rgba(224, 17, 95, 0.1)',
      card:       'rgba(255, 0, 51, 0.05)',
      border:     'rgba(255, 102, 102, 0.3)',
      text:       '#FFFFFF',
      textMuted:  '#FF9999',
      btn:        '#E0115F',
      btnText:    '#ffffff',
      btnHover:   '#B3004C',
    },
  },
  sapphire_blue: {
    id: 'sapphire_blue',
    label: 'Sapphire Blue',
    style: 'precious cool',
    colors: {
      primary:    '#0F52BA',
      accent:     '#4B9CD3',
      highlight:  '#89CFF0',
      background: '#020C1B',
      surface:    'rgba(15, 82, 186, 0.15)',
      card:       'rgba(75, 156, 211, 0.1)',
      border:     'rgba(137, 207, 240, 0.2)',
      text:       '#E6F2FF',
      textMuted:  '#89CFF0',
      btn:        '#0F52BA',
      btnText:    '#ffffff',
      btnHover:   '#0A3D87',
    },
  },
  amber_glow: {
    id: 'amber_glow',
    label: 'Amber Glow',
    style: 'warm light',
    colors: {
      primary:    '#FFBF00',
      accent:     '#FFD700',
      highlight:  '#FFFACD',
      background: '#2C2C2C',
      surface:    'rgba(255, 191, 0, 0.05)',
      card:       'rgba(255, 215, 0, 0.05)',
      border:     'rgba(255, 250, 205, 0.2)',
      text:       '#FFFFE0',
      textMuted:  '#FFD700',
      btn:        '#FFBF00',
      btnText:    '#2C2C2C',
      btnHover:   '#E6AC00',
    },
  },
  lavender_mist: {
    id: 'lavender_mist',
    label: 'Lavender Mist',
    style: 'calm purple',
    colors: {
      primary:    '#B57EDC',
      accent:     '#D8BFD8',
      highlight:  '#E6E6FA',
      background: '#F8F7FF',
      surface:    'rgba(255, 255, 255, 0.8)',
      card:       '#FFFFFF',
      border:     '#DCD0FF',
      text:       '#4B0082',
      textMuted:  '#9370DB',
      btn:        '#B57EDC',
      btnText:    '#ffffff',
      btnHover:   '#9A5FC9',
    },
  },
  peach_soft: {
    id: 'peach_soft',
    label: 'Peach Soft',
    style: 'gentle warm',
    colors: {
      primary:    '#FFDAB9',
      accent:     '#FFCBA4',
      highlight:  '#FFE5B4',
      background: '#FFF5EE',
      surface:    'rgba(255, 255, 255, 0.9)',
      card:       '#FFFFFF',
      border:     '#FFDAB9',
      text:       '#8B4513',
      textMuted:  '#D2691E',
      btn:        '#FFDAB9',
      btnText:    '#8B4513',
      btnHover:   '#FFCBA4',
    },
  },
  mint_leaf: {
    id: 'mint_leaf',
    label: 'Mint Leaf',
    style: 'fresh cool',
    colors: {
      primary:    '#98FF98',
      accent:     '#AAFFAA',
      highlight:  '#F0FFF0',
      background: '#F5FFFA',
      surface:    'rgba(255, 255, 255, 0.8)',
      card:       '#FFFFFF',
      border:     '#98FF98',
      text:       '#006400',
      textMuted:  '#2E8B57',
      btn:        '#98FF98',
      btnText:    '#006400',
      btnHover:   '#77DD77',
    },
  },
  lemon_zest: {
    id: 'lemon_zest',
    label: 'Lemon Zest',
    style: 'citrus bright',
    colors: {
      primary:    '#FFF700',
      accent:     '#FFFF9F',
      highlight:  '#FFFFE0',
      background: '#FFFFF0',
      surface:    'rgba(255, 255, 255, 0.9)',
      card:       '#FFFFFF',
      border:     '#FFF700',
      text:       '#555500',
      textMuted:  '#AAAA00',
      btn:        '#FFF700',
      btnText:    '#555500',
      btnHover:   '#E6E600',
    },
  },
  grape_soda: {
    id: 'grape_soda',
    label: 'Grape Soda',
    style: 'fun purple',
    colors: {
      primary:    '#6F2DA8',
      accent:     '#9B59B6',
      highlight:  '#D2B4DE',
      background: '#F4ECF7',
      surface:    'rgba(255, 255, 255, 0.8)',
      card:       '#FFFFFF',
      border:     '#D2B4DE',
      text:       '#4A235A',
      textMuted:  '#884EA0',
      btn:        '#6F2DA8',
      btnText:    '#ffffff',
      btnHover:   '#5B2C8A',
    },
  },
  blueberry_smooth: {
    id: 'blueberry_smooth',
    label: 'Blueberry Smooth',
    style: 'deep fruit',
    colors: {
      primary:    '#4F86F7',
      accent:     '#89CFF0',
      highlight:  '#E1F5FE',
      background: '#F0F8FF',
      surface:    'rgba(255, 255, 255, 0.8)',
      card:       '#FFFFFF',
      border:     '#B3D9FF',
      text:       '#0D47A1',
      textMuted:  '#42A5F5',
      btn:        '#4F86F7',
      btnText:    '#ffffff',
      btnHover:   '#3366CC',
    },
  },
  strawberry_milk: {
    id: 'strawberry_milk',
    label: 'Strawberry Milk',
    style: 'sweet pink',
    colors: {
      primary:    '#FFC1CC',
      accent:     '#FFD1DC',
      highlight:  '#FFF0F5',
      background: '#FFF5F7',
      surface:    'rgba(255, 255, 255, 0.9)',
      card:       '#FFFFFF',
      border:     '#FFC1CC',
      text:       '#C2185B',
      textMuted:  '#E91E63',
      btn:        '#FFC1CC',
      btnText:    '#C2185B',
      btnHover:   '#FFA6B5',
    },
  },
  chocolate_delight: {
    id: 'chocolate_delight',
    label: 'Chocolate Delight',
    style: 'rich brown',
    colors: {
      primary:    '#7B3F00',
      accent:     '#A0522D',
      highlight:  '#D2691E',
      background: '#FFF8F0',
      surface:    'rgba(255, 255, 255, 0.8)',
      card:       '#FFFFFF',
      border:     '#D2691E',
      text:       '#3E2723',
      textMuted:  '#5D4037',
      btn:        '#7B3F00',
      btnText:    '#ffffff',
      btnHover:   '#5C2E00',
    },
  },
  vanilla_pod: {
    id: 'vanilla_pod',
    label: 'Vanilla Pod',
    style: 'creamy neutral',
    colors: {
      primary:    '#F3E5AB',
      accent:     '#FFF8DC',
      highlight:  '#FFFFF0',
      background: '#FFFFF5',
      surface:    'rgba(255, 255, 255, 0.95)',
      card:       '#FFFFFF',
      border:     '#F3E5AB',
      text:       '#5C4B2E',
      textMuted:  '#8B7D5A',
      btn:        '#F3E5AB',
      btnText:    '#5C4B2E',
      btnHover:   '#E6D59A',
    },
  },
  caramel_swirl: {
    id: 'caramel_swirl',
    label: 'Caramel Swirl',
    style: 'sweet brown',
    colors: {
      primary:    '#C68E17',
      accent:     '#DAA520',
      highlight:  '#F5DEB3',
      background: '#FFFDD0',
      surface:    'rgba(255, 255, 255, 0.8)',
      card:       '#FFFFFF',
      border:     '#F5DEB3',
      text:       '#654321',
      textMuted:  '#8B4513',
      btn:        '#C68E17',
      btnText:    '#ffffff',
      btnHover:   '#A67511',
    },
  },
  matcha_latte: {
    id: 'matcha_latte',
    label: 'Matcha Latte',
    style: 'green tea',
    colors: {
      primary:    '#B4C99E',
      accent:     '#C5D8B0',
      highlight:  '#E8F5E9',
      background: '#F1F8E9',
      surface:    'rgba(255, 255, 255, 0.8)',
      card:       '#FFFFFF',
      border:     '#DCEDC8',
      text:       '#33691E',
      textMuted:  '#558B2F',
      btn:        '#B4C99E',
      btnText:    '#33691E',
      btnHover:   '#9CB885',
    },
  },
  coffee_beans: {
    id: 'coffee_beans',
    label: 'Coffee Beans',
    style: 'roast dark',
    colors: {
      primary:    '#6F4E37',
      accent:     '#8B5A2B',
      highlight:  '#D2B48C',
      background: '#2C241B',
      surface:    'rgba(111, 78, 55, 0.2)',
      card:       'rgba(139, 90, 43, 0.1)',
      border:     'rgba(210, 180, 140, 0.2)',
      text:       '#F5F5DC',
      textMuted:  '#BCA482',
      btn:        '#6F4E37',
      btnText:    '#ffffff',
      btnHover:   '#5A3E2B',
    },
  },
  tea_green: {
    id: 'tea_green',
    label: 'Tea Green',
    style: 'zen light',
    colors: {
      primary:    '#D0F0C0',
      accent:     '#E0F8D0',
      highlight:  '#F0FFF0',
      background: '#FAFFF5',
      surface:    'rgba(255, 255, 255, 0.9)',
      card:       '#FFFFFF',
      border:     '#D0F0C0',
      text:       '#2E5A1C',
      textMuted:  '#4F7A33',
      btn:        '#D0F0C0',
      btnText:    '#2E5A1C',
      btnHover:   '#B8E0A8',
    },
  },
  wine_cellar: {
    id: 'wine_cellar',
    label: 'Wine Cellar',
    style: 'rich red',
    colors: {
      primary:    '#722F37',
      accent:     '#903749',
      highlight:  '#B54C5E',
      background: '#2C1A1D',
      surface:    'rgba(114, 47, 55, 0.2)',
      card:       'rgba(144, 55, 73, 0.1)',
      border:     'rgba(181, 76, 94, 0.3)',
      text:       '#F8E8E8',
      textMuted:  '#D4A5A5',
      btn:        '#722F37',
      btnText:    '#ffffff',
      btnHover:   '#5A252B',
    },
  },
  champagne_bubbles: {
    id: 'champagne_bubbles',
    label: 'Champagne Bubbles',
    style: 'celebration',
    colors: {
      primary:    '#F7E7CE',
      accent:     '#FFF8E7',
      highlight:  '#FFFFF0',
      background: '#FAF9F6',
      surface:    'rgba(255, 255, 255, 0.9)',
      card:       '#FFFFFF',
      border:     '#F7E7CE',
      text:       '#5C4B2E',
      textMuted:  '#8B7D5A',
      btn:        '#F7E7CE',
      btnText:    '#5C4B2E',
      btnHover:   '#E6D5B8',
    },
  },
  copper_wire: {
    id: 'copper_wire',
    label: 'Copper Wire',
    style: 'metallic warm',
    colors: {
      primary:    '#B87333',
      accent:     '#DA8A67',
      highlight:  '#E6B89C',
      background: '#2B2B2B',
      surface:    'rgba(184, 115, 51, 0.1)',
      card:       'rgba(218, 138, 103, 0.05)',
      border:     'rgba(230, 184, 156, 0.2)',
      text:       '#F5F5F5',
      textMuted:  '#D4A574',
      btn:        '#B87333',
      btnText:    '#ffffff',
      btnHover:   '#9C612B',
    },
  },
  bronze_statue: {
    id: 'bronze_statue',
    label: 'Bronze Statue',
    style: 'antique metal',
    colors: {
      primary:    '#CD7F32',
      accent:     '#E6A86C',
      highlight:  '#F0C88C',
      background: '#1C1C1C',
      surface:    'rgba(205, 127, 50, 0.1)',
      card:       'rgba(230, 168, 108, 0.05)',
      border:     'rgba(240, 200, 140, 0.2)',
      text:       '#E0E0E0',
      textMuted:  '#C4A574',
      btn:        '#CD7F32',
      btnText:    '#ffffff',
      btnHover:   '#A8662A',
    },
  },
  iron_man: {
    id: 'iron_man',
    label: 'Iron Man',
    style: 'strong gray',
    colors: {
      primary:    '#707070',
      accent:     '#A0A0A0',
      highlight:  '#D0D0D0',
      background: '#1A1A1A',
      surface:    'rgba(112, 112, 112, 0.1)',
      card:       'rgba(160, 160, 160, 0.05)',
      border:     'rgba(208, 208, 208, 0.2)',
      text:       '#EEEEEE',
      textMuted:  '#AAAAAA',
      btn:        '#707070',
      btnText:    '#ffffff',
      btnHover:   '#555555',
    },
  },
  steel_gray: {
    id: 'steel_gray',
    label: 'Steel Gray',
    style: 'industrial cool',
    colors: {
      primary:    '#71797E',
      accent:     '#9CA3AF',
      highlight:  '#D1D5DB',
      background: '#1F2937',
      surface:    'rgba(113, 121, 126, 0.1)',
      card:       'rgba(156, 163, 175, 0.05)',
      border:     'rgba(209, 213, 219, 0.2)',
      text:       '#F3F4F6',
      textMuted:  '#9CA3AF',
      btn:        '#71797E',
      btnText:    '#ffffff',
      btnHover:   '#5B6165',
    },
  },
  titanium_white: {
    id: 'titanium_white',
    label: 'Titanium White',
    style: 'clean strong',
    colors: {
      primary:    '#E5E7EB',
      accent:     '#F3F4F6',
      highlight:  '#F9FAFB',
      background: '#FFFFFF',
      surface:    '#FFFFFF',
      card:       '#FFFFFF',
      border:     '#E5E7EB',
      text:       '#111827',
      textMuted:  '#6B7280',
      btn:        '#111827',
      btnText:    '#ffffff',
      btnHover:   '#000000',
    },
  },
  plasma_blue: {
    id: 'plasma_blue',
    label: 'Plasma Blue',
    style: 'electric energy',
    colors: {
      primary:    '#0055FF',
      accent:     '#0088FF',
      highlight:  '#00CCFF',
      background: '#000033',
      surface:    'rgba(0, 85, 255, 0.1)',
      card:       'rgba(0, 136, 255, 0.05)',
      border:     'rgba(0, 204, 255, 0.3)',
      text:       '#E6F2FF',
      textMuted:  '#80B3FF',
      btn:        '#0055FF',
      btnText:    '#ffffff',
      btnHover:   '#0044CC',
    },
  },
  laser_red: {
    id: 'laser_red',
    label: 'Laser Red',
    style: 'sharp focus',
    colors: {
      primary:    '#FF0000',
      accent:     '#FF3333',
      highlight:  '#FF6666',
      background: '#1A0000',
      surface:    'rgba(255, 0, 0, 0.05)',
      card:       'rgba(255, 51, 51, 0.05)',
      border:     'rgba(255, 102, 102, 0.3)',
      text:       '#FFFFFF',
      textMuted:  '#FF9999',
      btn:        '#FF0000',
      btnText:    '#ffffff',
      btnHover:   '#CC0000',
    },
  },
  hologram_silver: {
    id: 'hologram_silver',
    label: 'Hologram Silver',
    style: 'futuristic light',
    colors: {
      primary:    '#C0C0C0',
      accent:     '#E0E0E0',
      highlight:  '#F0F0F0',
      background: '#0A0A0A',
      surface:    'rgba(192, 192, 192, 0.05)',
      card:       'rgba(224, 224, 224, 0.05)',
      border:     'rgba(240, 240, 240, 0.2)',
      text:       '#FFFFFF',
      textMuted:  '#BBBBBB',
      btn:        '#C0C0C0',
      btnText:    '#0A0A0A',
      btnHover:   '#A0A0A0',
    },
  },
  galaxy_purple: {
    id: 'galaxy_purple',
    label: 'Galaxy Purple',
    style: 'space deep',
    colors: {
      primary:    '#6A0DAD',
      accent:     '#9370DB',
      highlight:  '#D8BFD8',
      background: '#0F001A',
      surface:    'rgba(106, 13, 173, 0.1)',
      card:       'rgba(147, 112, 219, 0.05)',
      border:     'rgba(216, 191, 216, 0.2)',
      text:       '#F3E5F5',
      textMuted:  '#CE93D8',
      btn:        '#6A0DAD',
      btnText:    '#ffffff',
      btnHover:   '#550A8A',
    },
  },
  starlight_white: {
    id: 'starlight_white',
    label: 'Starlight White',
    style: 'pure bright',
    colors: {
      primary:    '#FFFFFF',
      accent:     '#F0F0F0',
      highlight:  '#E0E0E0',
      background: '#FAFAFA',
      surface:    '#FFFFFF',
      card:       '#FFFFFF',
      border:     '#EEEEEE',
      text:       '#000000',
      textMuted:  '#666666',
      btn:        '#000000',
      btnText:    '#ffffff',
      btnHover:   '#333333',
    },
  },
  eclipse_black: {
    id: 'eclipse_black',
    label: 'Eclipse Black',
    style: 'void dark',
    colors: {
      primary:    '#333333',
      accent:     '#555555',
      highlight:  '#777777',
      background: '#000000',
      surface:    'rgba(50, 50, 50, 0.5)',
      card:       'rgba(80, 80, 80, 0.3)',
      border:     'rgba(120, 120, 120, 0.2)',
      text:       '#FFFFFF',
      textMuted:  '#AAAAAA',
      btn:        '#333333',
      btnText:    '#ffffff',
      btnHover:   '#222222',
    },
  },
  sunrise_orange: {
    id: 'sunrise_orange',
    label: 'Sunrise Orange',
    style: 'morning warm',
    colors: {
      primary:    '#FF7F50',
      accent:     '#FFA07A',
      highlight:  '#FFDAB9',
      background: '#FFF5EE',
      surface:    'rgba(255, 255, 255, 0.8)',
      card:       '#FFFFFF',
      border:     '#FFDAB9',
      text:       '#8B4513',
      textMuted:  '#D2691E',
      btn:        '#FF7F50',
      btnText:    '#ffffff',
      btnHover:   '#E66A3C',
    },
  },
  twilight_purple: {
    id: 'twilight_purple',
    label: 'Twilight Purple',
    style: 'evening calm',
    colors: {
      primary:    '#4B0082',
      accent:     '#8A2BE2',
      highlight:  '#9370DB',
      background: '#1A0524',
      surface:    'rgba(75, 0, 130, 0.2)',
      card:       'rgba(138, 43, 226, 0.1)',
      border:     'rgba(147, 112, 219, 0.3)',
      text:       '#E6E6FA',
      textMuted:  '#B0A4E3',
      btn:        '#8A2BE2',
      btnText:    '#ffffff',
      btnHover:   '#7A26C9',
    },
  },
  noon_yellow: {
    id: 'noon_yellow',
    label: 'Noon Yellow',
    style: 'bright day',
    colors: {
      primary:    '#FFD700',
      accent:     '#FFEA00',
      highlight:  '#FFFFE0',
      background: '#FFFFF0',
      surface:    'rgba(255, 255, 255, 0.9)',
      card:       '#FFFFFF',
      border:     '#FFD700',
      text:       '#555500',
      textMuted:  '#888800',
      btn:        '#FFD700',
      btnText:    '#555500',
      btnHover:   '#E6C200',
    },
  },
  dusk_pink: {
    id: 'dusk_pink',
    label: 'Dusk Pink',
    style: 'evening soft',
    colors: {
      primary:    '#FFC0CB',
      accent:     '#FFB6C1',
      highlight:  '#FFE4E1',
      background: '#FFF0F5',
      surface:    'rgba(255, 255, 255, 0.8)',
      card:       '#FFFFFF',
      border:     '#FFC0CB',
      text:       '#8B4557',
      textMuted:  '#B76E79',
      btn:        '#FFC0CB',
      btnText:    '#8B4557',
      btnHover:   '#FFA6B5',
    },
  },
  minty_fresh: {
    id: 'minty_fresh',
    label: 'Minty Fresh',
    style: 'pharmacie / hygiène',
    colors: {
      primary: '#34D399',
      accent: '#A7F3D0',
      highlight: '#ECFDF5',
      background: '#F0FFF9',
      surface: 'rgba(255,255,255,0.9)',
      card: '#FFFFFF',
      border: '#D1FAE5',
      text: '#064E3B',
      textMuted: '#6B7280',
      btn: '#34D399',
      btnText: '#064E3B',
      btnHover: '#10B981',
    },
  },

  lemon_clean: {
    id: 'lemon_clean',
    label: 'Lemon Clean',
    style: 'produits ménagers',
    colors: {
      primary: '#FACC15',
      accent: '#FEF08A',
      highlight: '#FEFCE8',
      background: '#FFFEF0',
      surface: 'rgba(255,255,255,0.9)',
      card: '#FFFFFF',
      border: '#FEF9C3',
      text: '#713F12',
      textMuted: '#A16207',
      btn: '#FACC15',
      btnText: '#713F12',
      btnHover: '#EAB308',
    },
  },

  peachy_store: {
    id: 'peachy_store',
    label: 'Peachy Store',
    style: 'lifestyle',
    colors: {
      primary: '#FDBA74',
      accent: '#FED7AA',
      highlight: '#FFF7ED',
      background: '#FFF9F5',
      surface: 'rgba(255,255,255,0.9)',
      card: '#FFFFFF',
      border: '#FED7AA',
      text: '#7C2D12',
      textMuted: '#9A3412',
      btn: '#FDBA74',
      btnText: '#7C2D12',
      btnHover: '#FB923C',
    },
  },

  lavender_soft: {
    id: 'lavender_soft',
    label: 'Lavender Soft',
    style: 'cosmétique',
    colors: {
      primary: '#C4B5FD',
      accent: '#DDD6FE',
      highlight: '#F5F3FF',
      background: '#FAF8FF',
      surface: 'rgba(255,255,255,0.9)',
      card: '#FFFFFF',
      border: '#EDE9FE',
      text: '#4C1D95',
      textMuted: '#7C3AED',
      btn: '#C4B5FD',
      btnText: '#4C1D95',
      btnHover: '#A78BFA',
    },
  },

  sky_breeze: {
    id: 'sky_breeze',
    label: 'Sky Breeze',
    style: 'clean tech',
    colors: {
      primary: '#38BDF8',
      accent: '#BAE6FD',
      highlight: '#E0F2FE',
      background: '#F5FBFF',
      surface: 'rgba(255,255,255,0.9)',
      card: '#FFFFFF',
      border: '#BAE6FD',
      text: '#0C4A6E',
      textMuted: '#0369A1',
      btn: '#38BDF8',
      btnText: '#ffffff',
      btnHover: '#0EA5E9',
    },
  },

  coral_soft: {
    id: 'coral_soft',
    label: 'Coral Soft',
    style: 'restaurant',
    colors: {
      primary: '#FB7185',
      accent: '#FECACA',
      highlight: '#FFF1F2',
      background: '#FFF5F6',
      surface: 'rgba(255,255,255,0.9)',
      card: '#FFFFFF',
      border: '#FECDD3',
      text: '#881337',
      textMuted: '#BE123C',
      btn: '#FB7185',
      btnText: '#ffffff',
      btnHover: '#E11D48',
    },
  },

  vanilla_cream: {
    id: 'vanilla_cream',
    label: 'Vanilla Cream',
    style: 'dessert',
    colors: {
      primary: '#FDE68A',
      accent: '#FEF3C7',
      highlight: '#FFFBEB',
      background: '#FFFDF7',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#FEF9C3',
      text: '#78350F',
      textMuted: '#A16207',
      btn: '#FDE68A',
      btnText: '#78350F',
      btnHover: '#FCD34D',
    },
  },

  blush_shop: {
    id: 'blush_shop',
    label: 'Blush Shop',
    style: 'beauty',
    colors: {
      primary: '#FDA4AF',
      accent: '#FFE4E6',
      highlight: '#FFF1F2',
      background: '#FFF7F8',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#FECDD3',
      text: '#881337',
      textMuted: '#9F1239',
      btn: '#FDA4AF',
      btnText: '#ffffff',
      btnHover: '#FB7185',
    },
  },

  aqua_soft: {
    id: 'aqua_soft',
    label: 'Aqua Soft',
    style: 'spa',
    colors: {
      primary: '#67E8F9',
      accent: '#CFFAFE',
      highlight: '#ECFEFF',
      background: '#F5FEFF',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#A5F3FC',
      text: '#164E63',
      textMuted: '#0891B2',
      btn: '#67E8F9',
      btnText: '#083344',
      btnHover: '#22D3EE',
    },
  },

  olive_nature: {
    id: 'olive_nature',
    label: 'Olive Nature',
    style: 'bio',
    colors: {
      primary: '#84CC16',
      accent: '#D9F99D',
      highlight: '#F7FEE7',
      background: '#FAFFF5',
      surface: 'rgba(255,255,255,0.9)',
      card: '#FFFFFF',
      border: '#D9F99D',
      text: '#365314',
      textMuted: '#4D7C0F',
      btn: '#84CC16',
      btnText: '#ffffff',
      btnHover: '#65A30D',
    },
  },

  cherry_cute: {
    id: 'cherry_cute',
    label: 'Cherry Cute',
    style: 'snack',
    colors: {
      primary: '#EF4444',
      accent: '#FCA5A5',
      highlight: '#FEF2F2',
      background: '#FFF5F5',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#FECACA',
      text: '#7F1D1D',
      textMuted: '#991B1B',
      btn: '#EF4444',
      btnText: '#ffffff',
      btnHover: '#DC2626',
    },
  },

  milk_soft: {
    id: 'milk_soft',
    label: 'Milk Soft',
    style: 'minimal',
    colors: {
      primary: '#E5E7EB',
      accent: '#F3F4F6',
      highlight: '#FAFAFA',
      background: '#FFFFFF',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#E5E7EB',
      text: '#111827',
      textMuted: '#6B7280',
      btn: '#E5E7EB',
      btnText: '#111827',
      btnHover: '#D1D5DB',
    },
  },

  bubblegum_fun: {
    id: 'bubblegum_fun',
    label: 'Bubblegum Fun',
    style: 'kids',
    colors: {
      primary: '#F472B6',
      accent: '#FBCFE8',
      highlight: '#FDF2F8',
      background: '#FFF6FA',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#F9A8D4',
      text: '#831843',
      textMuted: '#9D174D',
      btn: '#F472B6',
      btnText: '#ffffff',
      btnHover: '#DB2777',
    },
  },

  fresh_orange: {
    id: 'fresh_orange',
    label: 'Fresh Orange',
    style: 'juice bar',
    colors: {
      primary: '#FB923C',
      accent: '#FED7AA',
      highlight: '#FFF7ED',
      background: '#FFF8F3',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#FDBA74',
      text: '#7C2D12',
      textMuted: '#C2410C',
      btn: '#FB923C',
      btnText: '#ffffff',
      btnHover: '#EA580C',
    },
  },

  pistachio_soft: {
    id: 'pistachio_soft',
    label: 'Pistachio Soft',
    style: 'food healthy',
    colors: {
      primary: '#A3E635',
      accent: '#D9F99D',
      highlight: '#F7FEE7',
      background: '#FBFFF5',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#D9F99D',
      text: '#365314',
      textMuted: '#4D7C0F',
      btn: '#A3E635',
      btnText: '#365314',
      btnHover: '#84CC16',
    },
  },

  cotton_candy: {
    id: 'cotton_candy',
    label: 'Cotton Candy',
    style: 'dessert fun',
    colors: {
      primary: '#F9A8D4',
      accent: '#C4B5FD',
      highlight: '#FDF4FF',
      background: '#FFF7FF',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#E9D5FF',
      text: '#6B21A8',
      textMuted: '#9333EA',
      btn: '#F9A8D4',
      btnText: '#6B21A8',
      btnHover: '#EC4899',
    },
  },

  clinic_light: {
    id: 'clinic_light',
    label: 'Clinic Light',
    style: 'clinique',
    colors: {
      primary: '#0EA5E9',
      accent: '#7DD3FC',
      highlight: '#E0F2FE',
      background: '#F7FCFF',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#BAE6FD',
      text: '#0C4A6E',
      textMuted: '#0369A1',
      btn: '#0EA5E9',
      btnText: '#ffffff',
      btnHover: '#0284C7',
    },
  },

  herb_green: {
    id: 'herb_green',
    label: 'Herb Green',
    style: 'phytothérapie',
    colors: {
      primary: '#22C55E',
      accent: '#BBF7D0',
      highlight: '#F0FDF4',
      background: '#F6FFF8',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#DCFCE7',
      text: '#14532D',
      textMuted: '#166534',
      btn: '#22C55E',
      btnText: '#ffffff',
      btnHover: '#16A34A',
    },
  },

  rose_gold_light: {
    id: 'rose_gold_light',
    label: 'Rose Gold Light',
    style: 'luxe doux',
    colors: {
      primary: '#F43F5E',
      accent: '#FECDD3',
      highlight: '#FFF1F2',
      background: '#FFF8F8',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#FECDD3',
      text: '#881337',
      textMuted: '#BE123C',
      btn: '#F43F5E',
      btnText: '#ffffff',
      btnHover: '#E11D48',
    },
  },

  clean_gray: {
    id: 'clean_gray',
    label: 'Clean Gray',
    style: 'pro minimal',
    colors: {
      primary: '#6B7280',
      accent: '#E5E7EB',
      highlight: '#F9FAFB',
      background: '#FFFFFF',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#E5E7EB',
      text: '#111827',
      textMuted: '#6B7280',
      btn: '#6B7280',
      btnText: '#ffffff',
      btnHover: '#4B5563',
    },
  },

  sky_pastel: {
    id: 'sky_pastel',
    label: 'Sky Pastel',
    style: 'kids / soft',
    colors: {
      primary: '#93C5FD',
      accent: '#BFDBFE',
      highlight: '#EFF6FF',
      background: '#F7FBFF',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#DBEAFE',
      text: '#1E3A8A',
      textMuted: '#3B82F6',
      btn: '#93C5FD',
      btnText: '#1E3A8A',
      btnHover: '#60A5FA',
    },
  },

  mango_smooth: {
    id: 'mango_smooth',
    label: 'Mango Smooth',
    style: 'smoothie',
    colors: {
      primary: '#FBBF24',
      accent: '#FDE68A',
      highlight: '#FFFBEB',
      background: '#FFFDF5',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#FEF3C7',
      text: '#78350F',
      textMuted: '#92400E',
      btn: '#FBBF24',
      btnText: '#78350F',
      btnHover: '#F59E0B',
    },
  },

  clean_teal: {
    id: 'clean_teal',
    label: 'Clean Teal',
    style: 'modern pro',
    colors: {
      primary: '#14B8A6',
      accent: '#99F6E4',
      highlight: '#F0FDFA',
      background: '#F7FFFD',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#CCFBF1',
      text: '#134E4A',
      textMuted: '#0F766E',
      btn: '#14B8A6',
      btnText: '#ffffff',
      btnHover: '#0D9488',
    },
  },

  soft_red_food: {
    id: 'soft_red_food',
    label: 'Soft Red Food',
    style: 'fast food',
    colors: {
      primary: '#F87171',
      accent: '#FECACA',
      highlight: '#FEF2F2',
      background: '#FFF7F7',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#FECACA',
      text: '#7F1D1D',
      textMuted: '#B91C1C',
      btn: '#F87171',
      btnText: '#ffffff',
      btnHover: '#EF4444',
    },
  },

  light_indigo: {
    id: 'light_indigo',
    label: 'Light Indigo',
    style: 'tech clean',
    colors: {
      primary: '#818CF8',
      accent: '#C7D2FE',
      highlight: '#EEF2FF',
      background: '#F8FAFF',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#E0E7FF',
      text: '#1E1B4B',
      textMuted: '#6366F1',
      btn: '#818CF8',
      btnText: '#ffffff',
      btnHover: '#6366F1',
    },
  },

  soft_brown: {
    id: 'soft_brown',
    label: 'Soft Brown',
    style: 'café chic',
    colors: {
      primary: '#A16207',
      accent: '#FDE68A',
      highlight: '#FFFBEB',
      background: '#FFFAF5',
      surface: 'rgba(255,255,255,0.95)',
      card: '#FFFFFF',
      border: '#FDE68A',
      text: '#78350F',
      textMuted: '#92400E',
      btn: '#A16207',
      btnText: '#ffffff',
      btnHover: '#78350F',
    },
  },

  pure_white: {
    id: 'pure_white',
    label: 'Pure White',
    style: 'ultra minimal',
    colors: {
      primary: '#111827',
      accent: '#E5E7EB',
      highlight: '#F9FAFB',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      card: '#FFFFFF',
      border: '#F3F4F6',
      text: '#111827',
      textMuted: '#6B7280',
      btn: '#111827',
      btnText: '#ffffff',
      btnHover: '#000000',
    },
  },
  zecks_dark_pro: {
    id: 'zecks_dark_pro',
    label: 'Zecks Dark Pro',
    style: 'smartphone premium / dark UI',
    colors: {
      primary:    '#6C63FF',
      accent:     '#00D1FF',
      highlight:  '#8B5CF6',
      background: '#0F172A',
      surface:    'rgba(30, 41, 59, 0.65)',
      card:       'rgba(51, 65, 85, 0.55)',
      border:     'rgba(255,255,255,0.08)',
      text:       '#F8FAFC',
      textMuted:  '#94A3B8',
      btn:        'linear-gradient(135deg, #6C63FF, #8B5CF6)',
      btnText:    '#ffffff',
      btnHover:   '#5A52E0',
    },
  },

  midnight_glass: {
    id: 'midnight_glass',
    label: 'Midnight Glass',
    style: 'glassmorphism tech',
    colors: {
      primary:    '#4F46E5',
      accent:     '#22D3EE',
      highlight:  '#A78BFA',
      background: '#020617',
      surface:    'rgba(255,255,255,0.05)',
      card:       'rgba(255,255,255,0.08)',
      border:     'rgba(255,255,255,0.12)',
      text:       '#E2E8F0',
      textMuted:  '#64748B',
      btn:        '#4F46E5',
      btnText:    '#ffffff',
      btnHover:   '#3730A3',
    },
  },

  neon_tech: {
    id: 'neon_tech',
    label: 'Neon Tech',
    style: 'gaming / gadgets',
    colors: {
      primary:    '#00FFA3',
      accent:     '#00E5FF',
      highlight:  '#39FF14',
      background: '#000000',
      surface:    'rgba(255,255,255,0.06)',
      card:       'rgba(0,255,163,0.08)',
      border:     'rgba(0,255,163,0.25)',
      text:       '#E5E7EB',
      textMuted:  '#6B7280',
      btn:        '#00FFA3',
      btnText:    '#000000',
      btnHover:   '#00cc82',
    },
  },

  luxury_phone: {
    id: 'luxury_phone',
    label: 'Luxury Phone',
    style: 'smartphone haut de gamme',
    colors: {
      primary:    '#C6A7FF',
      accent:     '#F59E0B',
      highlight:  '#E9D5FF',
      background: '#0A0A0B',
      surface:    '#141416',
      card:       '#1C1C1F',
      border:     'rgba(255,255,255,0.06)',
      text:       '#FAFAFA',
      textMuted:  '#A1A1AA',
      btn:        '#C6A7FF',
      btnText:    '#0A0A0B',
      btnHover:   '#A78BFA',
    },
  },

  ios_clean: {
    id: 'ios_clean',
    label: 'iOS Clean',
    style: 'apple-like minimal',
    colors: {
      primary:    '#007AFF',
      accent:     '#34C759',
      highlight:  '#5AC8FA',
      background: '#F2F2F7',
      surface:    'rgba(255,255,255,0.7)',
      card:       '#FFFFFF',
      border:     '#E5E7EB',
      text:       '#1D1D1F',
      textMuted:  '#6E6E73',
      btn:        '#007AFF',
      btnText:    '#ffffff',
      btnHover:   '#005ecb',
    },
  },

  sunset_commerce: {
    id: 'sunset_commerce',
    label: 'Sunset Commerce',
    style: 'promo / conversion',
    colors: {
      primary:    '#FF6B6B',
      accent:     '#FFD166',
      highlight:  '#FF8FA3',
      background: '#1E1E2F',
      surface:    'rgba(255,255,255,0.06)',
      card:       'rgba(255,255,255,0.08)',
      border:     'rgba(255,255,255,0.08)',
      text:       '#F9FAFB',
      textMuted:  '#9CA3AF',
      btn:        '#FF6B6B',
      btnText:    '#ffffff',
      btnHover:   '#e05555',
    },
  },

  cyber_blue: {
    id: 'cyber_blue',
    label: 'Cyber Blue',
    style: 'tech futuriste',
    colors: {
      primary:    '#00B4D8',
      accent:     '#0077B6',
      highlight:  '#90E0EF',
      background: '#03045E',
      surface:    'rgba(255,255,255,0.08)',
      card:       'rgba(0,180,216,0.12)',
      border:     'rgba(144,224,239,0.25)',
      text:       '#CAF0F8',
      textMuted:  '#90E0EF',
      btn:        '#00B4D8',
      btnText:    '#03045E',
      btnHover:   '#0096c7',
    },
  },

  minimal_dark_soft: {
    id: 'minimal_dark_soft',
    label: 'Minimal Dark Soft',
    style: 'boutique moderne',
    colors: {
      primary:    '#6366F1',
      accent:     '#A5B4FC',
      highlight:  '#818CF8',
      background: '#111827',
      surface:    'rgba(31,41,55,0.6)',
      card:       'rgba(55,65,81,0.6)',
      border:     'rgba(255,255,255,0.05)',
      text:       '#F9FAFB',
      textMuted:  '#9CA3AF',
      btn:        '#6366F1',
      btnText:    '#ffffff',
      btnHover:   '#4F46E5',
    },
  },
  dark_premium: { 
    id: 'dark_premium', 
    label: 'Dark mode premium', 
    style: 'e-commerce luxe moderne', 
    colors: { 
      primary: '#C6A7FF', 
      accent: '#2EE6C9', 
      highlight: '#FF8FA3', 
      background: '#0A0A0B', 
      surface: '#141416', 
      text: '#F5F5F7', 
      textMuted: '#A1A1AA', 
      btn: '#C6A7FF', 
      btnText: '#0A0A0B', 
      btnHover: '#A78BFA', 
    }, 
  },
};
export const DEFAULT_THEME = 'dark_premium';